

WEEK_DAYS_OPENING_HOURS = {
    'mon': 'monday',
    'tue': 'tuesday',
    'wed': 'wednesday',
    'thu': 'thursday',
    'fri': 'friday',
    'sat': 'saturday',
    'sun': 'sunday',
}


us_states_dict = {
    "alabama": "AL",
    "alaska": "AK",
    "arizona": "AZ",
    "arkansas": "AR",
    "california": "CA",
    "colorado": "CO",
    "connecticut": "CT",
    "delaware": "DE",
    "florida": "FL",
    "georgia": "GA",
    "hawaii": "HI",
    "idaho": "ID",
    "illinois": "IL",
    "indiana": "IN",
    "iowa": "IA",
    "kansas": "KS",
    "kentucky": "KY",
    "louisiana": "LA",
    "maine": "ME",
    "maryland": "MD",
    "massachusetts": "MA",
    "michigan": "MI",
    "minnesota": "MN",
    "mississippi": "MS",
    "missouri": "MO",
    "montana": "MT",
    "nebraska": "NE",
    "nevada": "NV",
    "new hampshire": "NH",
    "new jersey": "NJ",
    "new mexico": "NM",
    "new york": "NY",
    "north carolina": "NC",
    "north dakota": "ND",
    "ohio": "OH",
    "oklahoma": "OK",
    "oregon": "OR",
    "pennsylvania": "PA",
    "rhode island": "RI",
    "south carolina": "SC",
    "south dakota": "SD",
    "tennessee": "TN",
    "texas": "TX",
    "utah": "UT",
    "vermont": "VT",
    "virginia": "VA",
    "washington": "WA",
    "west virginia": "WV",
    "wisconsin": "WI",
    "wyoming": "WY",
}


project = {
        # "name": 1,
        "google_id": 1,
        # "address": 1,
        # "phone_no": 1,
        # "website": 1,
        # "category_cuisine_google": 1,
        # "opening_hours": 1,
        "extracted_dishes": 1,
        # "img_url": 1,
        # "amenties": 1,
        # "lat": 1,
        # "long": 1,
        "published": 1,
        "published_at": 1,
        "republished_at": 1,
    }


# Formatting
state_code = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming",
}


# Formatting
stateCodeTOcityDict = {
    "TX": [
        "Abbott",
        "Abernathy",
        "Abilene",
        "Ace",
        "Ackerly",
        "Addison",
        "Adkins",
        "Adrian",
        "Afton",
        "Agua Dulce",
        "Aiken",
        "Alamo",
        "Alanreed",
        "Albany",
        "Aledo",
        "Alice",
        "Alief",
        "Allen",
        "Alleyton",
        "Allison",
        "Alpine",
        "Altair",
        "Alto",
        "Alvarado",
        "Alvin",
        "Alvord",
        "Amarillo",
        "Amherst",
        "Anahuac",
        "Anderson",
        "Andrews",
        "Angleton",
        "Angus",
        "Anna",
        "Annona",
        "Anson",
        "Anthony",
        "Anton",
        "Apple Springs",
        "Aquilla",
        "Aransas Pass",
        "Archer City",
        "Argyle",
        "Arlington",
        "Armstrong",
        "Arp",
        "Art",
        "Artesia Wells",
        "Arthur City",
        "Asherton",
        "Aspermont",
        "Atascosa",
        "Athens",
        "Atlanta",
        "Aubrey",
        "Austin",
        "Austwell",
        "Avalon",
        "Avery",
        "Avinger",
        "Avoca",
        "Axtell",
        "Azle",
        "Bacliff",
        "Bagwell",
        "Bailey",
        "Baird",
        "Ballinger",
        "Balmorhea",
        "Bandera",
        "Bangs",
        "Banquete",
        "Bardwell",
        "Barker",
        "Barksdale",
        "Barnhart",
        "Barry",
        "Barstow",
        "Bartlett",
        "Bastrop",
        "Batesville",
        "Batson",
        "Bay City",
        "Bayside",
        "Baytown",
        "Beasley",
        "Beaumont",
        "Bebe",
        "Beckville",
        "Bedford",
        "Bedias",
        "Bee Cave",
        "Beeville",
        "Bellaire",
        "Bellevue",
        "Bellville",
        "Belmont",
        "Belton",
        "Ben Bolt",
        "Ben Franklin",
        "Ben Wheeler",
        "Benavides",
        "Bend",
        "Benjamin",
        "Berclair",
        "Bergheim",
        "Bertram",
        "Big Bend National Park",
        "Big Sandy",
        "Big Spring",
        "Big Wells",
        "Bigfoot",
        "Bishop",
        "Bivins",
        "Blackwell",
        "Blanco",
        "Blanket",
        "Bledsoe",
        "Bleiblerville",
        "Blessing",
        "Bloomburg",
        "Blooming Grove",
        "Bloomington",
        "Blossom",
        "Blue Ridge",
        "Bluegrove",
        "Bluff Dale",
        "Bluffton",
        "Blum",
        "Boerne",
        "Bogata",
        "Boling",
        "Bon Wier",
        "Bonham",
        "Booker",
        "Borger",
        "Bovina",
        "Bowie",
        "Boyd",
        "Boys Ranch",
        "Brackettville",
        "Brady",
        "Brandon",
        "Brashear",
        "Brazoria",
        "Breckenridge",
        "Bremond",
        "Brenham",
        "Bridge City",
        "Briggs",
        "Briscoe",
        "Broaddus",
        "Bronson",
        "Bronte",
        "Brookeland",
        "Brookesmith",
        "Brookshire",
        "Brookston",
        "Brownfield",
        "Brownsboro",
        "Brownsville",
        "Brownwood",
        "Bruceville",
        "Bruni",
        "Bryan",
        "Bryson",
        "Buchanan Dam",
        "Buckholts",
        "Buda",
        "Buffalo Gap",
        "Buffalo",
        "Bula",
        "Bullard",
        "Bulverde",
        "Buna",
        "Burkburnett",
        "Burkeville",
        "Burleson",
        "Burlington",
        "Burnet",
        "Burton",
        "Bushland",
        "Byers",
        "Bynum",
        "Cactus",
        "Caddo Mills",
        "Caddo",
        "Caldwell",
        "Call",
        "Calliham",
        "Calvert",
        "Camden",
        "Cameron",
        "Camp Wood",
        "Campbell",
        "Campbellton",
        "Canadian",
        "Canton",
        "Canutillo",
        "Canyon Lake",
        "Canyon",
        "Carbon",
        "Carey",
        "Carlsbad",
        "Carlton",
        "Carmine",
        "Carrizo Springs",
        "Carrollton",
        "Carthage",
        "Cason",
        "Castell",
        "Castroville",
        "Cat Spring",
        "Catarina",
        "Cayuga",
        "Cedar Creek",
        "Cedar Hill",
        "Cedar Lane",
        "Cedar Park",
        "Cee Vee",
        "Celeste",
        "Celina",
        "Center Point",
        "Center",
        "Centerville",
        "Centralia",
        "Chalk",
        "Chandler",
        "Channelview",
        "Channing",
        "Chapman Ranch",
        "Chappell Hill",
        "Charlotte",
        "Chatfield",
        "Cherokee",
        "Chester",
        "Chico",
        "Chicota",
        "Childress",
        "Chillicothe",
        "Chilton",
        "China Spring",
        "China",
        "Chireno",
        "Chriesman",
        "Christine",
        "Christoval",
        "Cibolo",
        "Cisco",
        "Clarendon",
        "Clarksville",
        "Claude",
        "Clayton",
        "Cleburne",
        "Cleveland",
        "Clifton",
        "Clint",
        "Clute",
        "Clyde",
        "Coahoma",
        "Coldspring",
        "Coleman",
        "College Station",
        "Collegeport",
        "Colleyville",
        "Collinsville",
        "Colmesneil",
        "Colorado City",
        "Columbus",
        "Comanche",
        "Combes",
        "Comfort",
        "Commerce",
        "Como",
        "Comstock",
        "Concan",
        "Concepcion",
        "Concord",
        "Conroe",
        "Converse",
        "Cookville",
        "Coolidge",
        "Cooper",
        "Copeville",
        "Copperas Cove",
        "Corinth",
        "Corpus Christi",
        "Corrigan",
        "Corsicana",
        "Cost",
        "Cotton Center",
        "Cotulla",
        "Coupland",
        "Covington",
        "Coyanosa",
        "Crandall",
        "Crane",
        "Cranfills Gap",
        "Crawford",
        "Cresson",
        "Crockett",
        "Crosby",
        "Crosbyton",
        "Cross Plains",
        "Crowell",
        "Crowley",
        "Crystal City",
        "Cuero",
        "Cumby",
        "Cuney",
        "Cunningham",
        "Cushing",
        "Cypress",
        "D Hanis",
        "Daingerfield",
        "Daisetta",
        "Dale",
        "Dalhart",
        "Dallardsville",
        "Dallas",
        "Damon",
        "Danbury",
        "Danciger",
        "Danevang",
        "Darrouzett",
        "Davilla",
        "Dawn",
        "Dawson",
        "Dayton",
        "De Berry",
        "De Kalb",
        "De Leon",
        "Deanville",
        "Decatur",
        "Deer Park",
        "Del Rio",
        "Del Valle",
        "Dell City",
        "Delmita",
        "Denison",
        "Dennis",
        "Denton",
        "Denver City",
        "Deport",
        "Desdemona",
        "Desoto",
        "Detroit",
        "Devers",
        "Devine",
        "Deweyville",
        "Diana",
        "Diboll",
        "Dickens",
        "Dickinson",
        "Dike",
        "Dilley",
        "Dime Box",
        "Dimmitt",
        "Dinero",
        "Dobbin",
        "Dodd City",
        "Dodge",
        "Dodson",
        "Donie",
        "Donna",
        "Doole",
        "Doss",
        "Doucette",
        "Dougherty",
        "Douglass",
        "Douglassville",
        "Driftwood",
        "Dripping Springs",
        "Driscoll",
        "Dryden",
        "Dublin",
        "Dumas",
        "Dumont",
        "Duncanville",
        "Dunn",
        "Dyess AFB",
        "Eagle Lake",
        "Eagle Pass",
        "Early",
        "Earth",
        "East Bernard",
        "Eastland",
        "Ecleto",
        "Ector",
        "Edcouch",
        "Eddy",
        "Eden",
        "Edgewood",
        "Edinburg",
        "Edmonson",
        "Edna",
        "Edroy",
        "Egypt",
        "El Campo",
        "El Indio",
        "El Paso",
        "Eldorado",
        "Electra",
        "Elgin",
        "Elkhart",
        "Ellinger",
        "Elm Mott",
        "Elmaton",
        "Elmendorf",
        "Elmo",
        "Elsa",
        "Elysian Fields",
        "Emory",
        "Encinal",
        "Encino",
        "Energy",
        "Enloe",
        "Ennis",
        "Enochs",
        "Eola",
        "Era",
        "Estelline",
        "Etoile",
        "Euless",
        "Eustace",
        "Evadale",
        "Evant",
        "Fabens",
        "Fairfield",
        "Falcon Heights",
        "Falls City",
        "Fannin",
        "Farmersville",
        "Farnsworth",
        "Farwell",
        "Fate",
        "Fayetteville",
        "Fentress",
        "Ferris",
        "Fieldton",
        "Fischer",
        "Flat",
        "Flatonia",
        "Flint",
        "Flomot",
        "Florence",
        "Floresville",
        "Flower Mound",
        "Floydada",
        "Fluvanna",
        "Flynn",
        "Follett",
        "Forestburg",
        "Forney",
        "Forreston",
        "Forsan",
        "Fort Davis",
        "Fort Hancock",
        "Fort McKavett",
        "Fort Stockton",
        "Fowlerton",
        "Francitas",
        "Franklin",
        "Frankston",
        "Fred",
        "Fredericksburg",
        "Fredonia",
        "Freeport",
        "Freer",
        "Fresno",
        "Friendswood",
        "Friona",
        "Frisco",
        "Fritch",
        "Frost",
        "Fruitvale",
        "Fulshear",
        "Fulton",
        "Gail",
        "Gainesville",
        "Galena Park",
        "Gallatin",
        "Galveston",
        "Ganado",
        "Garciasville",
        "Garden City",
        "Gardendale",
        "Garland",
        "Garrison",
        "Garwood",
        "Gary",
        "Gatesville",
        "Gause",
        "Geneva",
        "Georgetown",
        "Geronimo",
        "Giddings",
        "Gilchrist",
        "Gillett",
        "Gilmer",
        "Girard",
        "Girvin",
        "Gladewater",
        "Glen Flora",
        "Glen Rose",
        "Glidden",
        "Gober",
        "Godley",
        "Golden",
        "Goldsboro",
        "Goldsmith",
        "Goliad",
        "Gonzales",
        "Goodfellow AFB",
        "Goodrich",
        "Gordon",
        "Gordonville",
        "Goree",
        "Gorman",
        "Gouldbusk",
        "Graford",
        "Graham",
        "Granbury",
        "Grand Prairie",
        "Grand Saline",
        "Grandfalls",
        "Grandview",
        "Granger",
        "Grapeland",
        "Grapevine",
        "Greenville",
        "Greenwood",
        "Gregory",
        "Groesbeck",
        "Groom",
        "Groves",
        "Groveton",
        "Grulla",
        "Gruver",
        "Guerra",
        "Gun Barrel City",
        "Gunter",
        "Gustine",
        "Guthrie",
        "Guy",
        "Hale Center",
        "Hallettsville",
        "Hallsville",
        "Haltom City",
        "Hamilton",
        "Hamlin",
        "Hamshire",
        "Hankamer",
        "Happy",
        "Hardin",
        "Hargill",
        "Harker Heights",
        "Harleton",
        "Harlingen",
        "Harper",
        "Harrold",
        "Hart",
        "Hartley",
        "Harwood",
        "Haskell",
        "Haslet",
        "Hawkins",
        "Hawley",
        "Hearne",
        "Hebbronville",
        "Hedley",
        "Heidenheimer",
        "Helotes",
        "Hemphill",
        "Hempstead",
        "Henderson",
        "Henrietta",
        "Hereford",
        "Hermleigh",
        "Hewitt",
        "Hext",
        "Hico",
        "Hidalgo",
        "Higgins",
        "Highlands",
        "Hillister",
        "Hillsboro",
        "Hitchcock",
        "Hobson",
        "Hochheim",
        "Hockley",
        "Holland",
        "Holliday",
        "Hondo",
        "Honey Grove",
        "Hooks",
        "Houston",
        "Howe",
        "Hubbard",
        "Huffman",
        "Hufsmith",
        "Hughes Springs",
        "Hull",
        "Humble",
        "Hungerford",
        "Hunt",
        "Huntington",
        "Huntsville",
        "Hurst",
        "Hutchins",
        "Hutto",
        "Hye",
        "Idalou",
        "Imperial",
        "Industry",
        "Inez",
        "Ingleside",
        "Ingram",
        "Iola",
        "Iowa Park",
        "Ira",
        "Iraan",
        "Iredell",
        "Irene",
        "Irving",
        "Italy",
        "Itasca",
        "Ivanhoe",
        "Jacksboro",
        "Jacksonville",
        "Jarrell",
        "Jasper",
        "Jefferson",
        "Jermyn",
        "Jewett",
        "Joaquin",
        "Johnson City",
        "Joinerville",
        "Jonesboro",
        "Jonesville",
        "Josephine",
        "Joshua",
        "Jourdanton",
        "Judson",
        "Junction",
        "Justiceburg",
        "Justin",
        "Kamay",
        "Karnack",
        "Karnes City",
        "Katy",
        "Keene",
        "Keller",
        "Kemah",
        "Kemp",
        "Kempner",
        "Kendalia",
        "Kendleton",
        "Kenedy",
        "Kennard",
        "Kennedale",
        "Kenney",
        "Kerens",
        "Kermit",
        "Kerrville",
        "Kildare",
        "Kilgore",
        "Killeen",
        "Kingsbury",
        "Kingsland",
        "Kirbyville",
        "Kirkland",
        "Kirvin",
        "Klondike",
        "Knickerbocker",
        "Knippa",
        "Knott",
        "Knox City",
        "Kopperl",
        "Kosse",
        "Kountze",
        "Kress",
        "Krum",
        "Kurten",
        "Kyle",
        "La Blanca",
        "La Coste",
        "La Feria",
        "La Grange",
        "La Joya",
        "La Marque",
        "La Porte",
        "La Pryor",
        "La Salle",
        "La Vernia",
        "La Victoria",
        "La Villa",
        "La Ward",
        "Ladonia",
        "Laguna Park",
        "Laird Hill",
        "Lake Creek",
        "Lake Dallas",
        "Lake Jackson",
        "Lakeview",
        "Lamesa",
        "Lampasas",
        "Lancaster",
        "Lane City",
        "Laneville",
        "Langtry",
        "Laredo",
        "Larue",
        "Lasara",
        "Latexo",
        "Laughlin A F B",
        "Lavon",
        "Lawn",
        "Lazbuddie",
        "League City",
        "Leakey",
        "Leander",
        "Ledbetter",
        "Leesburg",
        "Leesville",
        "Lefors",
        "Leggett",
        "Lelia Lake",
        "Leming",
        "Lenorah",
        "Leon Junction",
        "Leona",
        "Leonard",
        "Leroy",
        "Levelland",
        "Lewisville",
        "Lexington",
        "Liberty Hill",
        "Liberty",
        "Lillian",
        "Lincoln",
        "Lindale",
        "Linden",
        "Lindsay",
        "Lingleville",
        "Linn",
        "Lipan",
        "Lipscomb",
        "Lissie",
        "Little Elm",
        "Little River",
        "Littlefield",
        "Liverpool",
        "Livingston",
        "Llano",
        "Lockhart",
        "Lockney",
        "Lodi",
        "Lohn",
        "Lolita",
        "Lometa",
        "London",
        "Lone Oak",
        "Lone Star",
        "Long Branch",
        "Long Mott",
        "Longview",
        "Loop",
        "Lopeno",
        "Loraine",
        "Lorena",
        "Lorenzo",
        "Los Ebanos",
        "Los Fresnos",
        "Los Indios",
        "Lott",
        "Louise",
        "Lovelady",
        "Loving",
        "Lowake",
        "Lozano",
        "Lubbock",
        "Lueders",
        "Lufkin",
        "Luling",
        "Lumberton",
        "Lyford",
        "Lyons",
        "Lytle",
        "Mabank",
        "Macdona",
        "Madisonville",
        "Magnolia",
        "Malakoff",
        "Malone",
        "Manchaca",
        "Manor",
        "Mansfield",
        "Manvel",
        "Maple",
        "Marathon",
        "Marble Falls",
        "Marfa",
        "Marietta",
        "Marion",
        "Markham",
        "Marlin",
        "Marquez",
        "Marshall",
        "Mart",
        "Martindale",
        "Martinsville",
        "Maryneal",
        "Mason",
        "Masterson",
        "Matador",
        "Matagorda",
        "Mathis",
        "Maud",
        "Mauriceville",
        "Maxwell",
        "May",
        "Maydelle",
        "Maypearl",
        "Maysfield",
        "McAllen",
        "McCamey",
        "McCaulley",
        "McCoy",
        "McDade",
        "McGregor",
        "McKinney",
        "McLeod",
        "McNeil",
        "McQueeney",
        "Mcadoo",
        "Mcfaddin",
        "Mclean",
        "Meadow",
        "Medina",
        "Megargel",
        "Melissa",
        "Melvin",
        "Memphis",
        "Menard",
        "Mentone",
        "Mercedes",
        "Mereta",
        "Meridian",
        "Merit",
        "Merkel",
        "Mertens",
        "Mertzon",
        "Mesquite",
        "Mexia",
        "Meyersville",
        "Miami",
        "Mico",
        "Midfield",
        "Midkiff",
        "Midland",
        "Midlothian",
        "Midway",
        "Milam",
        "Milano",
        "Miles",
        "Milford",
        "Millersview",
        "Millican",
        "Millsap",
        "Minden",
        "Mineola",
        "Mineral Wells",
        "Mineral",
        "Mingus",
        "Mirando City",
        "Mission",
        "Missouri City",
        "Mobeetie",
        "Monahans",
        "Mont Belvieu",
        "Montague",
        "Montalba",
        "Montgomery",
        "Moody",
        "Moore",
        "Moran",
        "Morgan Mill",
        "Morgan",
        "Morse",
        "Morton",
        "Moscow",
        "Moulton",
        "Mound",
        "Mount Calm",
        "Mount Enterprise",
        "Mount Pleasant",
        "Mount Vernon",
        "Mountain Home",
        "Muenster",
        "Muldoon",
        "Muleshoe",
        "Mullin",
        "Mumford",
        "Munday",
        "Murchison",
        "Myra",
        "Nacogdoches",
        "Nada",
        "Naples",
        "Nash",
        "Natalia",
        "Naval Air Station/ Jrb",
        "Navasota",
        "Nazareth",
        "Neches",
        "Nederland",
        "Needville",
        "Nemo",
        "Nevada",
        "New Baden",
        "New Boston",
        "New Braunfels",
        "New Caney",
        "New Deal",
        "New Home",
        "New London",
        "New Summerfield",
        "New Ulm",
        "New Waverly",
        "Newark",
        "Newcastle",
        "Newgulf",
        "Newton",
        "Nixon",
        "Nocona",
        "Nolan",
        "Nolanville",
        "Nome",
        "Nordheim",
        "Normangee",
        "Normanna",
        "North Houston",
        "North Richland Hills",
        "North Zulch",
        "Norton",
        "Notrees",
        "Novice",
        "Nursery",
        "O Brien",
        "Oakhurst",
        "Oakland",
        "Oakville",
        "Oakwood",
        "Odell",
        "Odem",
        "Odessa",
        "Odonnell",
        "Oglesby",
        "Oilton",
        "Oklaunion",
        "Old Glory",
        "Old Ocean",
        "Olden",
        "Olmito",
        "Olney",
        "Olton",
        "Omaha",
        "Onalaska",
        "Orange Grove",
        "Orange",
        "Orangefield",
        "Orchard",
        "Ore City",
        "Orla",
        "Ottine",
        "Otto",
        "Ovalo",
        "Overton",
        "Ozona",
        "Paducah",
        "Paige",
        "Paint Rock",
        "Palacios",
        "Palestine",
        "Palmer",
        "Palo Pinto",
        "Paluxy",
        "Pampa",
        "Pandora",
        "Panhandle",
        "Panna Maria",
        "Panola",
        "Paradise",
        "Paris",
        "Pasadena",
        "Pattison",
        "Pattonville",
        "Pawnee",
        "Pear Valley",
        "Pearland",
        "Pearsall",
        "Peaster",
        "Pecan Gap",
        "Pecos",
        "Peggy",
        "Pendleton",
        "Penelope",
        "Penitas",
        "Pennington",
        "Penwell",
        "Pep",
        "Perrin",
        "Perry",
        "Perryton",
        "Petersburg",
        "Petrolia",
        "Pettus",
        "Petty",
        "Pflugerville",
        "Pharr",
        "Pickton",
        "Pierce",
        "Pilot Point",
        "Pinehurst",
        "Pineland",
        "Pipe Creek",
        "Pittsburg",
        "Placedo",
        "Plains",
        "Plainview",
        "Plano",
        "Plantersville",
        "Pleasanton",
        "Pledger",
        "Plum",
        "Point Comfort",
        "Point",
        "Pointblank",
        "Pollok",
        "Ponder",
        "Pontotoc",
        "Poolville",
        "Port Aransas",
        "Port Arthur",
        "Port Bolivar",
        "Port Isabel",
        "Port Lavaca",
        "Port Mansfield",
        "Port Neches",
        "Port O Connor",
        "Porter",
        "Portland",
        "Post",
        "Poteet",
        "Poth",
        "Pottsboro",
        "Pottsville",
        "Powderly",
        "Powell",
        "Poynor",
        "Prairie Hill",
        "Prairie Lea",
        "Prairie View",
        "Premont",
        "Presidio",
        "Price",
        "Priddy",
        "Princeton",
        "Proctor",
        "Progreso",
        "Prosper",
        "Purdon",
        "Purmela",
        "Putnam",
        "Pyote",
        "Quail",
        "Quanah",
        "Queen City",
        "Quemado",
        "Quinlan",
        "Quitaque",
        "Quitman",
        "Rainbow",
        "Ralls",
        "Rancho Alegre",
        "Randolph",
        "Ranger",
        "Rankin",
        "Ransom Canyon",
        "Ratcliff",
        "Ravenna",
        "Raymondville",
        "Raywood",
        "Reagan",
        "Realitos",
        "Red Oak",
        "Red Rock",
        "Redford",
        "Redwater",
        "Refugio",
        "Reklaw",
        "Rhome",
        "Rice",
        "Richards",
        "Richardson",
        "Richland Springs",
        "Richland",
        "Richmond",
        "Riesel",
        "Ringgold",
        "Rio Frio",
        "Rio Grande City",
        "Rio Hondo",
        "Rio Medina",
        "Rio Vista",
        "Rising Star",
        "Riverside",
        "Riviera",
        "Roanoke",
        "Roans Prairie",
        "Roaring Springs",
        "Robert Lee",
        "Robstown",
        "Roby",
        "Rochelle",
        "Rochester",
        "Rock Island",
        "Rockdale",
        "Rockport",
        "Rocksprings",
        "Rockwall",
        "Rockwood",
        "Rogers",
        "Roma",
        "Romayor",
        "Roosevelt",
        "Ropesville",
        "Rosanky",
        "Roscoe",
        "Rosebud",
        "Rosenberg",
        "Rosharon",
        "Ross",
        "Rosser",
        "Rosston",
        "Rotan",
        "Round Mountain",
        "Round Rock",
        "Round Top",
        "Rowena",
        "Rowlett",
        "Roxton",
        "Royalty",
        "Royse City",
        "Rule",
        "Runge",
        "Rusk",
        "Rye",
        "Sabinal",
        "Sabine Pass",
        "Sacul",
        "Sadler",
        "Saint Hedwig",
        "Saint Jo",
        "Salado",
        "Salineno",
        "Salt Flat",
        "Saltillo",
        "Samnorwood",
        "San Angelo",
        "San Antonio",
        "San Augustine",
        "San Benito",
        "San Diego",
        "San Elizario",
        "San Felipe",
        "San Isidro",
        "San Juan",
        "San Leon",
        "San Marcos",
        "San Perlita",
        "San Saba",
        "San Ygnacio",
        "Sanderson",
        "Sandia",
        "Sandy",
        "Sanford",
        "Sanger",
        "Santa Anna",
        "Santa Elena",
        "Santa Fe",
        "Santa Maria",
        "Santa Rosa",
        "Santo",
        "Saragosa",
        "Saratoga",
        "Sarita",
        "Satin",
        "Savoy",
        "Schertz",
        "Schulenburg",
        "Schwertner",
        "Scotland",
        "Scottsville",
        "Scroggins",
        "Scurry",
        "Seabrook",
        "Seadrift",
        "Seagoville",
        "Seagraves",
        "Sealy",
        "Sebastian",
        "Seguin",
        "Selman City",
        "Seminole",
        "Seymour",
        "Shafter",
        "Shallowater",
        "Shamrock",
        "Sheffield",
        "Shelbyville",
        "Shepherd",
        "Sheppard AFB",
        "Sheridan",
        "Sherman",
        "Shiner",
        "Shiro",
        "Sidney",
        "Sienna Plantation",
        "Sierra Blanca",
        "Silsbee",
        "Silver",
        "Silverton",
        "Simms",
        "Simonton",
        "Sinton",
        "Skellytown",
        "Skidmore",
        "Slaton",
        "Slidell",
        "Smiley",
        "Smithville",
        "Smyer",
        "Snook",
        "Snyder",
        "Somerset",
        "Somerville",
        "Sonora",
        "Sour Lake",
        "South Bend",
        "South Houston",
        "South Padre Island",
        "South Plains",
        "Southlake",
        "Southmayd",
        "Spade",
        "Speaks",
        "Spearman",
        "Spicewood",
        "Splendora",
        "Spring Branch",
        "Spring",
        "Springlake",
        "Springtown",
        "Spur",
        "Spurger",
        "Stafford",
        "Stamford",
        "Stanton",
        "Staples",
        "Star",
        "Stephenville",
        "Sterling City",
        "Stinnett",
        "Stockdale",
        "Stonewall",
        "Stowell",
        "Stratford",
        "Strawn",
        "Streetman",
        "Sublime",
        "Sudan",
        "Sugar Land",
        "Sullivan City",
        "Sulphur Bluff",
        "Sulphur Springs",
        "Summerfield",
        "Sumner",
        "Sundown",
        "Sunnyvale",
        "Sunray",
        "Sunset",
        "Sutherland Springs",
        "Sweeny",
        "Sweet Home",
        "Sweetwater",
        "Sylvester",
        "Taft",
        "Tahoka",
        "Talco",
        "Talpa",
        "Tarpley",
        "Tarzan",
        "Tatum",
        "Taylor",
        "Teague",
        "Tehuacana",
        "Telegraph",
        "Telephone",
        "Telferner",
        "Tell",
        "Temple",
        "Tenaha",
        "Tennessee Colony",
        "Tennyson",
        "Terlingua",
        "Terrell",
        "Texarkana",
        "Texas City",
        "Texline",
        "The Colony",
        "Thicket",
        "Thomaston",
        "Thompsons",
        "Thorndale",
        "Thornton",
        "Thrall",
        "Three Rivers",
        "Throckmorton",
        "Tilden",
        "Timpson",
        "Tioga",
        "Tivoli",
        "Tokio",
        "Tolar",
        "Tom Bean",
        "Tomball",
        "Tornillo",
        "Tow",
        "Toyah",
        "Toyahvale",
        "Trent",
        "Trenton",
        "Trinidad",
        "Trinity",
        "Troup",
        "Troy",
        "Tuleta",
        "Tulia",
        "Turkey",
        "Tuscola",
        "Tye",
        "Tyler",
        "Tynan",
        "Umbarger",
        "Universal City",
        "Utopia",
        "Uvalde",
        "Valentine",
        "Valera",
        "Valley Mills",
        "Valley Spring",
        "Valley View",
        "Van Alstyne",
        "Van Horn",
        "Van Vleck",
        "Van",
        "Vancourt",
        "Vanderbilt",
        "Vanderpool",
        "Vega",
        "Venus",
        "Veribest",
        "Vernon",
        "Victoria",
        "Vidor",
        "Village Mills",
        "Voca",
        "Von Ormy",
        "Voss",
        "Votaw",
        "Voth",
        "Waco",
        "Wadsworth",
        "Waelder",
        "Waka",
        "Walburg",
        "Wall",
        "Waller",
        "Wallis",
        "Wallisville",
        "Walnut Springs",
        "Warda",
        "Waring",
        "Warren",
        "Washington",
        "Waskom",
        "Water Valley",
        "Waxahachie",
        "Wayside",
        "Weatherford",
        "Webster",
        "Weesatche",
        "Weimar",
        "Weinert",
        "Weir",
        "Welch",
        "Wellborn",
        "Wellington",
        "Wellman",
        "Wells",
        "Weslaco",
        "West Columbia",
        "West Point",
        "West",
        "Westbrook",
        "Westhoff",
        "Westminster",
        "Weston",
        "Wharton",
        "Wheeler",
        "Wheelock",
        "White Deer",
        "White Oak",
        "Whiteface",
        "Whitehouse",
        "Whitesboro",
        "Whitewright",
        "Whitharral",
        "Whitney",
        "Whitsett",
        "Whitt",
        "Wichita Falls",
        "Wickett",
        "Wiergate",
        "Wildorado",
        "Willis",
        "Willow City",
        "Wills Point",
        "Wilmer",
        "Wilson",
        "Wimberley",
        "Windom",
        "Windthorst",
        "Winfield",
        "Wingate",
        "Wink",
        "Winnie",
        "Winnsboro",
        "Winona",
        "Winters",
        "Woden",
        "Wolfe City",
        "Wolfforth",
        "Woodlake",
        "Woodlawn",
        "Woodsboro",
        "Woodson",
        "Woodville",
        "Woodway",
        "Wortham",
        "Wrightsboro",
        "Wylie",
        "Yancey",
        "Yantis",
        "Yoakum",
        "Yorktown",
        "Zapata",
        "Zavalla",
        "Zephyr",
    ],
    "CA": [
        "Acton",
        "Adelanto",
        "Agoura Hills",
        "Alameda",
        "Alamo",
        "Albany",
        "Alhambra",
        "Aliso Viejo",
        "Alpaugh",
        "Alpine",
        "Altadena",
        "Alturas",
        "American Canyon",
        "Anaheim",
        "Anderson",
        "Angwin",
        "Antioch",
        "Apple Valley",
        "Aptos",
        "Arbuckle",
        "Arcadia",
        "Arcata",
        "Armona",
        "Arnold",
        "Aromas",
        "Arroyo Grande",
        "Artesia",
        "Arvin",
        "Atascadero",
        "Atherton",
        "Atwater",
        "Auberry",
        "Auburn",
        "Avalon",
        "Avenal",
        "Avery",
        "Azusa",
        "Bakersfield",
        "Baldwin Park",
        "Banning",
        "Barstow",
        "Beale Afb",
        "Beaumont",
        "Beckwourth",
        "Bell",
        "Bell Gardens",
        "Bellflower",
        "Belmont",
        "Ben Lomond",
        "Benicia",
        "Berkeley",
        "Bethel Island",
        "Beverly Hills",
        "Big Bear City",
        "Big Bear Lake",
        "Big Pine",
        "Biggs",
        "Biola",
        "Bishop",
        "Bloomington",
        "Blue Lake",
        "Blythe",
        "Bodega Bay",
        "Bodfish",
        "Bolinas",
        "Bonita",
        "Bonsall",
        "Boron",
        "Borrego Springs",
        "Boulder Creek",
        "Boyes Hot Springs",
        "Brawley",
        "Brea",
        "Brentwood",
        "Brisbane",
        "Buellton",
        "Buena Park",
        "Burbank",
        "Burlingame",
        "Burney",
        "Buttonwillow",
        "Byron",
        "Cabazon",
        "Calabasas",
        "Calexico",
        "California City",
        "Calimesa",
        "Calipatria",
        "Calistoga",
        "Camarillo",
        "Cambria",
        "Campbell",
        "Cantua Creek",
        "Capitola",
        "Carlsbad",
        "Carmel By The Sea",
        "Carmichael",
        "Carpinteria",
        "Carson",
        "Caruthers",
        "Castro Valley",
        "Castroville",
        "Cathedral City",
        "Cayucos",
        "Ceres",
        "Cerritos",
        "Chester",
        "Chico",
        "Chino",
        "Chino Hills",
        "Chowchilla",
        "Chualar",
        "Chula Vista",
        "Citrus Heights",
        "Claremont",
        "Clayton",
        "Clearlake",
        "Clearlake Oaks",
        "Cloverdale",
        "Clovis",
        "Coachella",
        "Coalinga",
        "Cobb",
        "Colfax",
        "Colton",
        "Columbia",
        "Colusa",
        "Compton",
        "Concord",
        "Copperopolis",
        "Corcoran",
        "Corning",
        "Corona",
        "Coronado",
        "Corte Madera",
        "Costa Mesa",
        "Cotati",
        "Cottonwood",
        "Covelo",
        "Covina",
        "Crescent City",
        "Crescent Mills",
        "Crestline",
        "Crockett",
        "Culver City",
        "Cupertino",
        "Cutler",
        "Cutten",
        "Cypress",
        "Daly City",
        "Dana Point",
        "Danville",
        "Davis",
        "Deer Park",
        "Del Mar",
        "Del Rey",
        "Delano",
        "Delhi",
        "Denair",
        "Desert Hot Springs",
        "Diablo",
        "Diamond Bar",
        "Diamond Springs",
        "Dillon Beach",
        "Dinuba",
        "Dixon",
        "Dorris",
        "Dos Palos",
        "Downey",
        "Duarte",
        "Dublin",
        "Ducor",
        "Dunsmuir",
        "Durham",
        "Earlimart",
        "El Cajon",
        "El Centro",
        "El Cerrito",
        "El Dorado Hills",
        "El Granada",
        "El Monte",
        "El Segundo",
        "El Sobrante",
        "El Verano",
        "Eldridge",
        "Elk Grove",
        "Elmira",
        "Emeryville",
        "Empire",
        "Encinitas",
        "Escalon",
        "Escondido",
        "Esparto",
        "Etna",
        "Eureka",
        "Exeter",
        "Fair Oaks",
        "Fairfax",
        "Fairfield",
        "Fall River Mills",
        "Fallbrook",
        "Farmersville",
        "Farmington",
        "Felton",
        "Ferndale",
        "Fillmore",
        "Firebaugh",
        "Folsom",
        "Fontana",
        "Foothill Ranch",
        "Foresthill",
        "Forestville",
        "Fort Bragg",
        "Fort Jones",
        "Fortuna",
        "Fountain Valley",
        "Fowler",
        "Frazier Park",
        "Freedom",
        "Fremont",
        "French Camp",
        "French Gulch",
        "Fresno",
        "Friant",
        "Fullerton",
        "Galt",
        "Garden Grove",
        "Gardena",
        "Georgetown",
        "Gilroy",
        "Glen Ellen",
        "Glendale",
        "Glendora",
        "Goleta",
        "Gonzales",
        "Goshen",
        "Grand Terrace",
        "Granite Bay",
        "Grass Valley",
        "Graton",
        "Greenfield",
        "Greenville",
        "Grenada",
        "Gridley",
        "Grover Beach",
        "Guadalupe",
        "Guerneville",
        "Gustine",
        "Hacienda Heights",
        "Half Moon Bay",
        "Hamilton City",
        "Hanford",
        "Hawaiian Gardens",
        "Hawthorne",
        "Hayfork",
        "Hayward",
        "Healdsburg",
        "Heber",
        "Hemet",
        "Hercules",
        "Hermosa Beach",
        "Hesperia",
        "Hickman",
        "Highland",
        "Hollister",
        "Holtville",
        "Homeland",
        "Hornbrook",
        "Hughson",
        "Huntington Beach",
        "Huntington Park",
        "Huron",
        "Hydesville",
        "Imperial",
        "Imperial Beach",
        "Independence",
        "Indian Wells",
        "Indio",
        "Inglewood",
        "Inverness",
        "Inyokern",
        "Ione",
        "Irvine",
        "Isleton",
        "Ivanhoe",
        "Jackson",
        "Jamestown",
        "Jamul",
        "Joshua Tree",
        "Julian",
        "Keene",
        "Kelseyville",
        "Kentfield",
        "Kerman",
        "Kernville",
        "Kettleman City",
        "Keyes",
        "King City",
        "Kings Beach",
        "Kingsburg",
        "Klamath",
        "Knightsen",
        "La Canada Flintridge",
        "La Habra",
        "La Mesa",
        "La Mirada",
        "La Palma",
        "La Puente",
        "La Quinta",
        "La Verne",
        "Lafayette",
        "Laguna Beach",
        "Laguna Hills",
        "Laguna Niguel",
        "Lake Arrowhead",
        "Lake Elsinore",
        "Lake Forest",
        "Lake Isabella",
        "Lakeport",
        "Lakeside",
        "Lakewood",
        "Lamont",
        "Lancaster",
        "Larkspur",
        "Lathrop",
        "Laton",
        "Lawndale",
        "Laytonville",
        "Le Grand",
        "Lebec",
        "Lemon Cove",
        "Lemon Grove",
        "Lemoore",
        "Lewiston",
        "Lincoln",
        "Linden",
        "Lindsay",
        "Littlerock",
        "Live Oak",
        "Livermore",
        "Livingston",
        "Lockeford",
        "Lodi",
        "Loma Linda",
        "Lomita",
        "Lompoc",
        "Lone Pine",
        "Long Beach",
        "Loomis",
        "Los Alamitos",
        "Los Alamos",
        "Los Altos",
        "Los Angeles",
        "Los Banos",
        "Los Gatos",
        "Los Molinos",
        "Lost Hills",
        "Lower Lake",
        "Loyalton",
        "Lucerne",
        "Lynwood",
        "Madera",
        "Magalia",
        "Malibu",
        "Mammoth Lakes",
        "Manhattan Beach",
        "Manteca",
        "Manton",
        "Maricopa",
        "Marina",
        "Marina Del Rey",
        "Mariposa",
        "Martinez",
        "Marysville",
        "Maywood",
        "Mc Farland",
        "Mcarthur",
        "Mccloud",
        "Mckinleyville",
        "Meadow Valley",
        "Meadow Vista",
        "Mecca",
        "Mendocino",
        "Mendota",
        "Menlo Park",
        "Mentone",
        "Merced",
        "Mi Wuk Village",
        "Middletown",
        "Mill Valley",
        "Millbrae",
        "Millville",
        "Milpitas",
        "Mira Loma",
        "Miramonte",
        "Mission Hills",
        "Mission Viejo",
        "Modesto",
        "Mojave",
        "Mokelumne Hill",
        "Monrovia",
        "Montague",
        "Montara",
        "Montclair",
        "Monte Rio",
        "Montebello",
        "Monterey",
        "Monterey Park",
        "Moorpark",
        "Moraga",
        "Moreno Valley",
        "Morgan Hill",
        "Morongo Valley",
        "Morro Bay",
        "Moss Beach",
        "Moss Landing",
        "Mount Shasta",
        "Mountain Ranch",
        "Mountain View",
        "Murphys",
        "Murrieta",
        "Napa",
        "National City",
        "Needles",
        "Nevada City",
        "Newark",
        "Newman",
        "Newport Beach",
        "Newport Coast",
        "Nice",
        "Niland",
        "Nipomo",
        "Norco",
        "North Highlands",
        "Norwalk",
        "Novato",
        "Nuevo",
        "Oak Park",
        "Oak View",
        "Oakdale",
        "Oakhurst",
        "Oakland",
        "Oakley",
        "Occidental",
        "Oceano",
        "Oceanside",
        "Ocotillo",
        "Ojai",
        "Olivehurst",
        "Ontario",
        "Onyx",
        "Orange",
        "Orange Cove",
        "Orangevale",
        "Orinda",
        "Orland",
        "Orosi",
        "Oroville",
        "Oxnard",
        "Pacific Grove",
        "Pacifica",
        "Palermo",
        "Palm Desert",
        "Palm Springs",
        "Palmdale",
        "Palo Alto",
        "Palo Cedro",
        "Palo Verde",
        "Paradise",
        "Paramount",
        "Parlier",
        "Pasadena",
        "Patterson",
        "Penn Valley",
        "Perris",
        "Petaluma",
        "Pico Rivera",
        "Piedmont",
        "Pine Valley",
        "Pinole",
        "Piru",
        "Pismo Beach",
        "Pittsburg",
        "Pixley",
        "Placentia",
        "Placerville",
        "Planada",
        "Pleasant Hill",
        "Pleasanton",
        "Plymouth",
        "Point Arena",
        "Point Reyes Station",
        "Pollock Pines",
        "Pomona",
        "Port Costa",
        "Port Hueneme",
        "Porterville",
        "Portola",
        "Portola Valley",
        "Poway",
        "Quincy",
        "Rail Road Flat",
        "Ramona",
        "Rancho Cordova",
        "Rancho Cucamonga",
        "Rancho Mirage",
        "Rancho Palos Verdes",
        "Rancho Santa Margarita",
        "Red Bluff",
        "Redding",
        "Redlands",
        "Redondo Beach",
        "Redway",
        "Redwood City",
        "Reedley",
        "Rialto",
        "Richgrove",
        "Richmond",
        "Ridgecrest",
        "Rio Dell",
        "Rio Linda",
        "Rio Vista",
        "Ripon",
        "Riverbank",
        "Riverdale",
        "Riverside",
        "Rocklin",
        "Rodeo",
        "Rohnert Park",
        "Rosamond",
        "Rosemead",
        "Roseville",
        "Ross",
        "Rowland Heights",
        "Running Springs",
        "Sacramento",
        "Salida",
        "Salinas",
        "Salton City",
        "San Andreas",
        "San Anselmo",
        "San Ardo",
        "San Bernardino",
        "San Bruno",
        "San Carlos",
        "San Clemente",
        "San Diego",
        "San Dimas",
        "San Fernando",
        "San Francisco",
        "San Gabriel",
        "San Geronimo",
        "San Jacinto",
        "San Joaquin",
        "San Jose",
        "San Juan Bautista",
        "San Juan Capistrano",
        "San Leandro",
        "San Lorenzo",
        "San Lucas",
        "San Luis Obispo",
        "San Marcos",
        "San Marino",
        "San Martin",
        "San Mateo",
        "San Miguel",
        "San Pablo",
        "San Rafael",
        "San Ramon",
        "Sanger",
        "Santa Ana",
        "Santa Barbara",
        "Santa Clara",
        "Santa Clarita",
        "Santa Cruz",
        "Santa Fe Springs",
        "Santa Maria",
        "Santa Monica",
        "Santa Paula",
        "Santa Rosa",
        "Santa Ynez",
        "Santee",
        "Saratoga",
        "Sausalito",
        "Scotts Valley",
        "Seal Beach",
        "Seaside",
        "Sebastopol",
        "Seeley",
        "Selma",
        "Shafter",
        "Shandon",
        "Shasta Lake",
        "Shaver Lake",
        "Shingle Springs",
        "Shingletown",
        "Sierra Madre",
        "Signal Hill",
        "Simi Valley",
        "Solana Beach",
        "Soledad",
        "Solvang",
        "Sonoma",
        "Sonora",
        "Soquel",
        "Soulsbyville",
        "South Dos Palos",
        "South El Monte",
        "South Gate",
        "South Lake Tahoe",
        "South Pasadena",
        "South San Francisco",
        "Spreckels",
        "Spring Valley",
        "Springville",
        "Squaw Valley",
        "Stanford",
        "Stanton",
        "Stinson Beach",
        "Stockton",
        "Stratford",
        "Strathmore",
        "Strawberry",
        "Suisun City",
        "Summerland",
        "Sun City",
        "Sunnyvale",
        "Sunol",
        "Susanville",
        "Sutter",
        "Sutter Creek",
        "Taft",
        "Tahoe Vista",
        "Talmage",
        "Tehachapi",
        "Tehama",
        "Temecula",
        "Temple City",
        "Templeton",
        "Terra Bella",
        "Thousand Oaks",
        "Thousand Palms",
        "Three Rivers",
        "Tipton",
        "Tomales",
        "Torrance",
        "Tracy",
        "Tranquillity",
        "Traver",
        "Trinidad",
        "Truckee",
        "Tulare",
        "Tulelake",
        "Tupman",
        "Turlock",
        "Tustin",
        "Twain Harte",
        "Twentynine Palms",
        "Ukiah",
        "Union City",
        "Upland",
        "Upper Lake",
        "Vacaville",
        "Vallecito",
        "Vallejo",
        "Valley Center",
        "Valley Springs",
        "Victorville",
        "Villa Park",
        "Visalia",
        "Vista",
        "Wallace",
        "Walnut",
        "Walnut Creek",
        "Walnut Grove",
        "Wasco",
        "Waterford",
        "Watsonville",
        "Weaverville",
        "Weed",
        "Weldon",
        "West Covina",
        "West Hollywood",
        "West Point",
        "West Sacramento",
        "Westlake Village",
        "Westley",
        "Westminster",
        "Westmorland",
        "Westwood",
        "Wheatland",
        "Whittier",
        "Wildomar",
        "Williams",
        "Willits",
        "Willow Creek",
        "Willows",
        "Wilton",
        "Winchester",
        "Windsor",
        "Winterhaven",
        "Winters",
        "Winton",
        "Wofford Heights",
        "Woodacre",
        "Woodlake",
        "Woodland",
        "Wrightwood",
        "Yorba Linda",
        "Yountville",
        "Yreka",
        "Yuba City",
        "Yucaipa",
        "Yucca Valley",
    ],
    "NY": [
        "Accord",
        "Adams Center",
        "Adams",
        "Addison",
        "Afton",
        "Akron",
        "Albany",
        "Albertson",
        "Albion",
        "Alden",
        "Alexander",
        "Alexandria Bay",
        "Alfred",
        "Allegany",
        "Allentown",
        "Alma",
        "Almond",
        "Altamont",
        "Altmar",
        "Altona",
        "Amagansett",
        "Amenia",
        "Amityville",
        "Amsterdam",
        "Ancram",
        "Andes",
        "Andover",
        "Angelica",
        "Angola",
        "Antwerp",
        "Apalachin",
        "Aquebogue",
        "Arcade",
        "Ardsley",
        "Argyle",
        "Arkport",
        "Armonk",
        "Ashland",
        "Athens",
        "Atlantic Beach",
        "Attica",
        "Au Sable Forks",
        "Auburn",
        "Aurora",
        "Austerlitz",
        "Ava",
        "Averill Park",
        "Avoca",
        "Avon",
        "Babylon",
        "Bainbridge",
        "Baldwin",
        "Baldwinsville",
        "Ballston Lake",
        "Ballston Spa",
        "Barker",
        "Barneveld",
        "Barton",
        "Batavia",
        "Bath",
        "Bay Shore",
        "Bayport",
        "Bayville",
        "Beacon",
        "Bedford",
        "Belfast",
        "Bellerose",
        "Bellmore",
        "Bellport",
        "Belmont",
        "Bemus Point",
        "Bergen",
        "Berkshire",
        "Berlin",
        "Berne",
        "Bethel",
        "Bethpage",
        "Big Flats",
        "Binghamton",
        "Black River",
        "Blauvelt",
        "Bloomfield",
        "Blooming Grove",
        "Bloomingburg",
        "Blue Point",
        "Bohemia",
        "Bolivar",
        "Bolton Landing",
        "Bombay",
        "Boonville",
        "Boston",
        "Bovina Center",
        "Bradford",
        "Brant",
        "Brasher Falls",
        "Brentwood",
        "Brewerton",
        "Brewster",
        "Briarcliff Manor",
        "Bridgehampton",
        "Bridgeport",
        "Bridgewater",
        "Brightwaters",
        "Broadalbin",
        "Brockport",
        "Brocton",
        "Bronxville",
        "Brookfield",
        "Brookhaven",
        "Brownville",
        "Brushton",
        "Buchanan",
        "Buffalo",
        "Burdett",
        "Burke",
        "Burlington Flats",
        "Byron",
        "Cairo",
        "Calcium",
        "Caledonia",
        "Callicoon",
        "Calverton",
        "Cambria Heights",
        "Cambridge",
        "Camden",
        "Cameron",
        "Camillus",
        "Campbell",
        "Canaan",
        "Canajoharie",
        "Canandaigua",
        "Canaseraga",
        "Canastota",
        "Candor",
        "Caneadea",
        "Canisteo",
        "Canton",
        "Cape Vincent",
        "Carle Place",
        "Carlisle",
        "Carmel",
        "Caroga Lake",
        "Carthage",
        "Cassadaga",
        "Castile",
        "Castleton On Hudson",
        "Castorland",
        "Cato",
        "Catskill",
        "Cattaraugus",
        "Cayuga",
        "Cayuta",
        "Cazenovia",
        "Cedarhurst",
        "Celoron",
        "Center Moriches",
        "Centereach",
        "Centerport",
        "Centerville",
        "Central Islip",
        "Central Square",
        "Central Valley",
        "Champlain",
        "Chappaqua",
        "Charlotteville",
        "Chateaugay",
        "Chatham",
        "Chaumont",
        "Chautauqua",
        "Chazy",
        "Chemung",
        "Chenango Bridge",
        "Chenango Forks",
        "Cherry Creek",
        "Cherry Valley",
        "Chester",
        "Chittenango",
        "Churchville",
        "Cicero",
        "Cincinnatus",
        "Clarence Center",
        "Clarence",
        "Clarendon",
        "Clark Mills",
        "Clarkson",
        "Clarksville",
        "Claverack",
        "Clay",
        "Clayton",
        "Clayville",
        "Cleveland",
        "Clifton Park",
        "Clifton Springs",
        "Clinton",
        "Clintondale",
        "Clyde",
        "Clymer",
        "Cobleskill",
        "Cochecton",
        "Coeymans",
        "Cohocton",
        "Cohoes",
        "Cold Brook",
        "Cold Spring Harbor",
        "Cold Spring",
        "Colden",
        "Collins",
        "Colton",
        "Commack",
        "Conesus",
        "Conewango Valley",
        "Congers",
        "Conklin",
        "Constable",
        "Constableville",
        "Constantia",
        "Cooperstown",
        "Copake",
        "Copenhagen",
        "Copiague",
        "Coram",
        "Corfu",
        "Corinth",
        "Corning",
        "Cornwall On Hudson",
        "Cornwall",
        "Cortland",
        "Cortlandt Manor",
        "Coxsackie",
        "Cragsmoor",
        "Croghan",
        "Crompond",
        "Croton On Hudson",
        "Crown Point",
        "Cuba",
        "Cutchogue",
        "Dannemora",
        "Dansville",
        "Darien Center",
        "Davenport",
        "Dayton",
        "De Kalb Junction",
        "De Peyster",
        "De Ruyter",
        "Deer Park",
        "Deferiet",
        "Delanson",
        "Delevan",
        "Delhi",
        "Delmar",
        "Denmark",
        "Depauville",
        "Depew",
        "Deposit",
        "Dexter",
        "Dickinson Center",
        "Dobbs Ferry",
        "Dolgeville",
        "Dover Plains",
        "Dresden",
        "Dryden",
        "Duanesburg",
        "Dundee",
        "Dunkirk",
        "Durham",
        "Eagle Bay",
        "Eagle Bridge",
        "Earlville",
        "East Aurora",
        "East Bloomfield",
        "East Greenbush",
        "East Hampton",
        "East Islip",
        "East Marion",
        "East Meadow",
        "East Moriches",
        "East Nassau",
        "East Northport",
        "East Norwich",
        "East Otto",
        "East Quogue",
        "East Randolph",
        "East Rochester",
        "East Rockaway",
        "East Syracuse",
        "East Williamson",
        "Eastchester",
        "Eastport",
        "Eaton",
        "Eden",
        "Edmeston",
        "Edwards",
        "Elba",
        "Elbridge",
        "Elizabethtown",
        "Ellenburg",
        "Ellenville",
        "Ellicottville",
        "Ellington",
        "Ellisburg",
        "Elma",
        "Elmira",
        "Elmont",
        "Elmsford",
        "Endicott",
        "Endwell",
        "Erin",
        "Esopus",
        "Esperance",
        "Essex",
        "Evans Mills",
        "Fabius",
        "Fair Haven",
        "Fairport",
        "Falconer",
        "Fallsburg",
        "Farmingdale",
        "Farmington",
        "Farmingville",
        "Farnham",
        "Fayette",
        "Fayetteville",
        "Fine",
        "Fishers Island",
        "Fishkill",
        "Fleischmanns",
        "Floral Park",
        "Florida",
        "Fonda",
        "Forestburgh",
        "Forestport",
        "Forestville",
        "Fort Ann",
        "Fort Covington",
        "Fort Drum",
        "Fort Edward",
        "Fort Johnson",
        "Fort Montgomery",
        "Fort Plain",
        "Frankfort",
        "Franklin Square",
        "Franklin",
        "Franklinville",
        "Fredonia",
        "Freedom",
        "Freeport",
        "Freeville",
        "Fremont Center",
        "Frewsburg",
        "Friendship",
        "Fulton",
        "Fultonville",
        "Gainesville",
        "Galway",
        "Garden City",
        "Gardiner",
        "Gasport",
        "Geneseo",
        "Geneva",
        "Genoa",
        "Georgetown",
        "Germantown",
        "Gerry",
        "Ghent",
        "Gilbertsville",
        "Gilboa",
        "Glasco",
        "Glen Cove",
        "Glen Head",
        "Glens Falls",
        "Glenwood Landing",
        "Gloversville",
        "Gorham",
        "Goshen",
        "Gouverneur",
        "Gowanda",
        "Grafton",
        "Grand Island",
        "Granville",
        "Great Bend",
        "Great Neck",
        "Great River",
        "Great Valley",
        "Greene",
        "Greenfield Center",
        "Greenlawn",
        "Greenport",
        "Greenvale",
        "Greenville",
        "Greenwich",
        "Greenwood Lake",
        "Greenwood",
        "Greig",
        "Groton",
        "Groveland",
        "Guilderland",
        "Guilford",
        "Hadley",
        "Hagaman",
        "Hague",
        "Hamburg",
        "Hamden",
        "Hamilton",
        "Hamlin",
        "Hammond",
        "Hammondsport",
        "Hampton Bays",
        "Hampton",
        "Hancock",
        "Hannibal",
        "Harford",
        "Harpersfield",
        "Harriman",
        "Harris",
        "Harrison",
        "Harrisville",
        "Hartford",
        "Hartsdale",
        "Hartwick",
        "Hastings On Hudson",
        "Hastings",
        "Hauppauge",
        "Haverstraw",
        "Hawthorne",
        "Hector",
        "Hempstead",
        "Henderson",
        "Henrietta",
        "Herkimer",
        "Hermon",
        "Heuvelton",
        "Hewlett",
        "Hicksville",
        "High Falls",
        "Highland Falls",
        "Highland Mills",
        "Highland",
        "Hillburn",
        "Hillsdale",
        "Hilton",
        "Hinsdale",
        "Hobart",
        "Holbrook",
        "Holland Patent",
        "Holland",
        "Holley",
        "Holtsville",
        "Homer",
        "Honeoye Falls",
        "Hoosick Falls",
        "Hoosick",
        "Hopewell Junction",
        "Hornell",
        "Horseheads",
        "Houghton",
        "Howard Beach",
        "Hudson Falls",
        "Hudson",
        "Hume",
        "Hunter",
        "Huntington Station",
        "Huntington",
        "Hurley",
        "Hyde Park",
        "Ilion",
        "Indian Lake",
        "Inlet",
        "Interlaken",
        "Inwood",
        "Irvington",
        "Island Park",
        "Islandia",
        "Islip Terrace",
        "Islip",
        "Ithaca",
        "Jackson Heights",
        "Jamesport",
        "Jamestown",
        "Jasper",
        "Java Center",
        "Jay",
        "Jefferson Valley",
        "Jefferson",
        "Jeffersonville",
        "Jericho",
        "Jewett",
        "Johnsburg",
        "Johnson City",
        "Johnstown",
        "Jordan",
        "Keene",
        "Keeseville",
        "Kendall",
        "Kent",
        "Kerhonkson",
        "Kinderhook",
        "Kings Park",
        "Kingston",
        "Kirkwood",
        "Knox",
        "La Fargeville",
        "La Fayette",
        "Lacona",
        "Lake George",
        "Lake Grove",
        "Lake Katrine",
        "Lake Luzerne",
        "Lake Placid",
        "Lake Pleasant",
        "Lake View",
        "Lakewood",
        "Lancaster",
        "Lansing",
        "Larchmont",
        "Laurel",
        "Laurens",
        "Lawrence",
        "Le Roy",
        "Lee Center",
        "Leeds",
        "Leicester",
        "Leon",
        "Levittown",
        "Lewis",
        "Lewiston",
        "Lexington",
        "Liberty",
        "Lima",
        "Limestone",
        "Lincolndale",
        "Lindenhurst",
        "Lindley",
        "Lisbon",
        "Lisle",
        "Little Falls",
        "Little Valley",
        "Liverpool",
        "Livingston Manor",
        "Livingston",
        "Livonia",
        "Locke",
        "Lockport",
        "Locust Valley",
        "Lodi",
        "Long Beach",
        "Long Lake",
        "Lorraine",
        "Lowville",
        "Lynbrook",
        "Lyndonville",
        "Lyon Mountain",
        "Lyons Falls",
        "Lyons",
        "Macedon",
        "Machias",
        "Madison",
        "Madrid",
        "Mahopac",
        "Maine",
        "Malden Bridge",
        "Malone",
        "Malverne",
        "Mamaroneck",
        "Manchester",
        "Manhasset",
        "Manlius",
        "Mannsville",
        "Manorville",
        "Marathon",
        "Marcellus",
        "Marcy",
        "Margaretville",
        "Marilla",
        "Marion",
        "Marlboro",
        "Martinsburg",
        "Maryland",
        "Masonville",
        "Massapequa Park",
        "Massapequa",
        "Massena",
        "Mastic Beach",
        "Mastic",
        "Mattituck",
        "Maybrook",
        "Mayfield",
        "Mayville",
        "Mc Donough",
        "Mc Graw",
        "Mechanicville",
        "Medford",
        "Medina",
        "Medusa",
        "Melrose",
        "Melville",
        "Mendon",
        "Meridian",
        "Merrick",
        "Mexico",
        "Mid Island",
        "Middleburgh",
        "Middleport",
        "Middlesex",
        "Middletown",
        "Middleville",
        "Milford",
        "Mill Neck",
        "Millbrook",
        "Miller Place",
        "Millerton",
        "Millport",
        "Milton",
        "Mineola",
        "Minerva",
        "Minetto",
        "Mineville",
        "Minoa",
        "Mohawk",
        "Moira",
        "Monroe",
        "Monsey",
        "Montauk",
        "Montezuma",
        "Montgomery",
        "Monticello",
        "Montour Falls",
        "Mooers",
        "Moravia",
        "Moriah",
        "Moriches",
        "Morris",
        "Morrisonville",
        "Morristown",
        "Morrisville",
        "Mount Kisco",
        "Mount Morris",
        "Mount Sinai",
        "Mount Vernon",
        "Munnsville",
        "Nanuet",
        "Napanoch",
        "Naples",
        "Narrowsburg",
        "Nassau",
        "Natural Bridge",
        "Nedrow",
        "Nelliston",
        "Nesconset",
        "Neversink",
        "New Baltimore",
        "New Berlin",
        "New City",
        "New Hartford",
        "New Haven",
        "New Hyde Park",
        "New Lebanon",
        "New Lisbon",
        "New Paltz",
        "New Rochelle",
        "New Suffolk",
        "New Windsor",
        "New York Mills",
        "New York",
        "Newark Valley",
        "Newark",
        "Newburgh",
        "Newcomb",
        "Newfane",
        "Newfield",
        "Newport",
        "Niagara Falls",
        "Nichols",
        "Niverville",
        "Norfolk",
        "North Babylon",
        "North Bay",
        "North Boston",
        "North Collins",
        "North Hudson",
        "North Norwich",
        "North Salem",
        "North Tonawanda",
        "Northport",
        "Northville",
        "Norwich",
        "Norwood",
        "Nunda",
        "Nyack",
        "Oakdale",
        "Oakfield",
        "Oceanside",
        "Odessa",
        "Ogdensburg",
        "Olcott",
        "Old Bethpage",
        "Old Westbury",
        "Olean",
        "Oneida",
        "Oneonta",
        "Ontario",
        "Orangeburg",
        "Orchard Park",
        "Orient",
        "Oriskany Falls",
        "Oriskany",
        "Orwell",
        "Ossining",
        "Oswegatchie",
        "Oswego",
        "Otego",
        "Otisville",
        "Otto",
        "Ovid",
        "Owego",
        "Oxford",
        "Oyster Bay",
        "Painted Post",
        "Palatine Bridge",
        "Palenville",
        "Palmyra",
        "Panama",
        "Parish",
        "Parishville",
        "Patchogue",
        "Patterson",
        "Pavilion",
        "Pearl River",
        "Peconic",
        "Peekskill",
        "Pelham",
        "Penfield",
        "Penn Yan",
        "Perry",
        "Perrysburg",
        "Peru",
        "Petersburg",
        "Phelps",
        "Philadelphia",
        "Philmont",
        "Phoenicia",
        "Phoenix",
        "Piercefield",
        "Piermont",
        "Pike",
        "Pine Bush",
        "Pine Hill",
        "Pine Plains",
        "Pitcher",
        "Pittsford",
        "Plainview",
        "Plattekill",
        "Plattsburgh",
        "Pleasant Valley",
        "Pleasantville",
        "Plymouth",
        "Poestenkill",
        "Point Lookout",
        "Poland",
        "Pomona",
        "Pompey",
        "Port Byron",
        "Port Chester",
        "Port Ewen",
        "Port Henry",
        "Port Jefferson Station",
        "Port Jefferson",
        "Port Jervis",
        "Port Leyden",
        "Port Washington",
        "Portageville",
        "Porter Corners",
        "Portland",
        "Portville",
        "Potsdam",
        "Poughkeepsie",
        "Pound Ridge",
        "Prattsburgh",
        "Prattsville",
        "Preble",
        "Preston Hollow",
        "Prospect",
        "Pulaski",
        "Pulteney",
        "Putnam Station",
        "Putnam Valley",
        "Quogue",
        "Randolph",
        "Ransomville",
        "Ravena",
        "Reading Center",
        "Red Creek",
        "Red Hook",
        "Redfield",
        "Redford",
        "Redwood",
        "Remsen",
        "Remsenburg",
        "Rensselaer Falls",
        "Rensselaer",
        "Rensselaerville",
        "Rhinebeck",
        "Richburg",
        "Richfield Springs",
        "Richford",
        "Richland",
        "Richmond Hill",
        "Richmondville",
        "Richville",
        "Ridge",
        "Rifton",
        "Ripley",
        "Riverhead",
        "Rochester",
        "Rock Hill",
        "Rockville Centre",
        "Rocky Point",
        "Rodman",
        "Rome",
        "Romulus",
        "Ronkonkoma",
        "Roosevelt",
        "Roscoe",
        "Rose",
        "Roseboom",
        "Rosendale",
        "Roslyn Heights",
        "Roslyn",
        "Rotterdam Junction",
        "Round Lake",
        "Rouses Point",
        "Roxbury",
        "Rush",
        "Rushford",
        "Rushville",
        "Russell",
        "Rye",
        "Sackets Harbor",
        "Sag Harbor",
        "Sagaponack",
        "Saint Bonaventure",
        "Saint James",
        "Saint Johnsville",
        "Salamanca",
        "Salem",
        "Salisbury Center",
        "Sand Lake",
        "Sandy Creek",
        "Sangerfield",
        "Saranac Lake",
        "Saranac",
        "Saratoga Springs",
        "Sardinia",
        "Saugerties",
        "Savannah",
        "Savona",
        "Sayville",
        "Scarsdale",
        "Schaghticoke",
        "Schenectady",
        "Schodack Landing",
        "Schoharie",
        "Schroon Lake",
        "Schuyler Falls",
        "Schuyler Lake",
        "Schuylerville",
        "Scio",
        "Scipio Center",
        "Scottsville",
        "Sea Cliff",
        "Seaford",
        "Selden",
        "Seneca Falls",
        "Shandaken",
        "Sharon Springs",
        "Shelter Island Heights",
        "Shelter Island",
        "Shenorock",
        "Sherburne",
        "Sheridan",
        "Sherman",
        "Sherrill",
        "Shirley",
        "Shokan",
        "Shoreham",
        "Shortsville",
        "Shrub Oak",
        "Sidney",
        "Silver Creek",
        "Silver Springs",
        "Sinclairville",
        "Skaneateles",
        "Sloatsburg",
        "Smyrna",
        "Sodus Point",
        "Sodus",
        "Somers",
        "Sound Beach",
        "South Dayton",
        "South Fallsburg",
        "South Glens Falls",
        "Southampton",
        "Southold",
        "Speculator",
        "Spencer",
        "Spencerport",
        "Spring Valley",
        "Springville",
        "Staatsburg",
        "Stafford",
        "Stamford",
        "Stanfordville",
        "Star Lake",
        "Stephentown",
        "Sterling",
        "Stillwater",
        "Stockton",
        "Stone Ridge",
        "Stony Brook",
        "Stony Creek",
        "Stony Point",
        "Stratford",
        "Stuyvesant",
        "Suffern",
        "Summit",
        "Sylvan Beach",
        "Syosset",
        "Syracuse",
        "Tannersville",
        "Tappan",
        "Tarrytown",
        "Theresa",
        "Thiells",
        "Thompsonville",
        "Thornwood",
        "Ticonderoga",
        "Tillson",
        "Tioga Center",
        "Tomkins Cove",
        "Tonawanda",
        "Tribes Hill",
        "Troupsburg",
        "Troy",
        "Trumansburg",
        "Truxton",
        "Tuckahoe",
        "Tully",
        "Tupper Lake",
        "Turin",
        "Tuxedo Park",
        "Tyrone",
        "Ulster Park",
        "Unadilla",
        "Union Hill",
        "Union Springs",
        "Uniondale",
        "Unionville",
        "Utica",
        "Vails Gate",
        "Valatie",
        "Valhalla",
        "Valley Cottage",
        "Valley Falls",
        "Valley Stream",
        "Van Buren Point",
        "Van Etten",
        "Vernon",
        "Verona",
        "Verplanck",
        "Vestal",
        "Victor",
        "Victory Mills",
        "Voorheesville",
        "Waddington",
        "Wading River",
        "Wainscott",
        "Walden",
        "Wales Center",
        "Walker Valley",
        "Wallkill",
        "Walton",
        "Walworth",
        "Wampsville",
        "Wantagh",
        "Wappingers Falls",
        "Warrensburg",
        "Warsaw",
        "Warwick",
        "Washington Mills",
        "Washingtonville",
        "Waterford",
        "Waterloo",
        "Watertown",
        "Waterville",
        "Watervliet",
        "Watkins Glen",
        "Waverly",
        "Wawarsing",
        "Wayland",
        "Wayne",
        "Webster",
        "Weedsport",
        "Wells",
        "Wellsburg",
        "Wellsville",
        "West Babylon",
        "West Bloomfield",
        "West Haverstraw",
        "West Hempstead",
        "West Hurley",
        "West Islip",
        "West Monroe",
        "West Nyack",
        "West Point",
        "West Sand Lake",
        "West Sayville",
        "West Winfield",
        "Westbury",
        "Westerlo",
        "Westernville",
        "Westfield",
        "Westford",
        "Westhampton Beach",
        "Westhampton",
        "Westmoreland",
        "Westons Mills",
        "Westport",
        "White Plains",
        "Whitehall",
        "Whitesboro",
        "Whitney Point",
        "Willet",
        "Williamson",
        "Williamstown",
        "Williston Park",
        "Willsboro",
        "Wilmington",
        "Wilson",
        "Windham",
        "Windsor",
        "Wolcott",
        "Woodbury",
        "Woodhull",
        "Woodmere",
        "Woodridge",
        "Woodstock",
        "Worcester",
        "Wurtsboro",
        "Wyandanch",
        "Wynantskill",
        "Wyoming",
        "Yaphank",
        "Yonkers",
        "York",
        "Yorkshire",
        "Yorktown Heights",
        "Yorkville",
        "Youngstown",
    ],
    "FL": [
        "Alachua",
        "Alford",
        "Altamonte Springs",
        "Altha",
        "Anna Maria",
        "Apalachicola",
        "Apopka",
        "Arcadia",
        "Archer",
        "Astatula",
        "Atlantic Beach",
        "Atlantis",
        "Auburndale",
        "Aventura",
        "Avon Park",
        "Bal Harbour",
        "Baldwin",
        "Bartow",
        "Bascom",
        "Bay Harbor Islands",
        "Bay Lake",
        "Bell",
        "Belle Glade",
        "Belle Isle",
        "Belleair Beach",
        "Belleair Bluffs",
        "Belleair Shore",
        "Belleair",
        "Belleview",
        "Beverly Beach",
        "Biscayne Park",
        "Blountstown",
        "Boca Raton",
        "Bonifay",
        "Bonita Springs",
        "Bowling Green",
        "Boynton Beach",
        "Bradenton Beach",
        "Bradenton",
        "Branford",
        "Briny Breezes",
        "Bristol",
        "Bronson",
        "Brooker",
        "Brooksville",
        "Bunnell",
        "Bushnell",
        "Callahan",
        "Callaway",
        "Campbellton",
        "Cape Canaveral",
        "Cape Coral",
        "Carrabelle",
        "Caryville",
        "Casselberry",
        "Cedar Key",
        "Center Hill",
        "Century",
        "Chattahoochee",
        "Chiefland",
        "Chipley",
        "Cinco Bayou",
        "Clearwater",
        "Clermont",
        "Clewiston",
        "Cloud Lake",
        "Cocoa Beach",
        "Cocoa",
        "Coconut Creek",
        "Coleman",
        "Cooper City",
        "Coral Gables",
        "Coral Springs",
        "Cottondale",
        "Crescent City",
        "Crestview",
        "Cross City",
        "Crystal River",
        "Cutler Bay",
        "Dade City",
        "Dania Beach",
        "Davenport",
        "Davie",
        "Daytona Beach Shores",
        "Daytona Beach",
        "DeBary",
        "DeFuniak Springs",
        "DeLand",
        "Deerfield Beach",
        "Delray Beach",
        "Deltona",
        "Destin",
        "Doral",
        "Dundee",
        "Dunedin",
        "Dunnellon",
        "Eagle Lake",
        "Eatonville",
        "Ebro",
        "Edgewater",
        "Edgewood",
        "El Portal",
        "Estero",
        "Esto",
        "Eustis",
        "Everglades City",
        "Fanning Springs",
        "Fellsmere",
        "Fernandina Beach",
        "Flagler Beach",
        "Florida City",
        "Fort Lauderdale",
        "Fort Meade",
        "Fort Myers Beach",
        "Fort Myers",
        "Fort Pierce",
        "Fort Walton Beach",
        "Fort White",
        "Freeport",
        "Frostproof",
        "Fruitland Park",
        "Gainesville",
        "Glen Ridge",
        "Glen St. Mary",
        "Golden Beach",
        "Golf",
        "Graceville",
        "Grand Ridge",
        "Grant-Valkaria",
        "Green Cove Springs",
        "Greenacres",
        "Greensboro",
        "Greenville",
        "Greenwood",
        "Gretna",
        "Groveland",
        "Gulf Breeze",
        "Gulf Stream",
        "Gulfport",
        "Haines City",
        "Hallandale Beach",
        "Hampton",
        "Havana",
        "Haverhill",
        "Hawthorne",
        "Hialeah Gardens",
        "Hialeah",
        "High Springs",
        "Highland Beach",
        "Highland Park",
        "Hillcrest Heights",
        "Hilliard",
        "Hillsboro Beach",
        "Holly Hill",
        "Hollywood",
        "Holmes Beach",
        "Homestead",
        "Horseshoe Beach",
        "Howey-in-the-Hills",
        "Hypoluxo",
        "Indialantic",
        "Indian Creek",
        "Indian Harbour Beach",
        "Indian River Shores",
        "Indian Rocks Beach",
        "Indian Shores",
        "Indiantown",
        "Inglis",
        "Interlachen",
        "Inverness",
        "Islamorada",
        "Jacksonville Beach",
        "Jacksonville",
        "Jacob City",
        "Jasper",
        "Jay",
        "Jennings",
        "Juno Beach",
        "Jupiter Inlet Colony",
        "Jupiter Island",
        "Jupiter",
        "Kenneth City",
        "Key Biscayne",
        "Key Colony Beach",
        "Key West",
        "Keystone Heights",
        "Kissimmee",
        "LaBelle",
        "LaCrosse",
        "Lady Lake",
        "Lake Alfred",
        "Lake Buena Vista",
        "Lake Butler",
        "Lake City",
        "Lake Clarke Shores",
        "Lake Hamilton",
        "Lake Helen",
        "Lake Mary",
        "Lake Park",
        "Lake Placid",
        "Lake Wales",
        "Lake Worth Beach",
        "Lakeland",
        "Lantana",
        "Largo",
        "Lauderdale Lakes",
        "Lauderdale-by-the-Sea",
        "Lauderhill",
        "Laurel Hill",
        "Lawtey",
        "Layton",
        "Lazy Lake",
        "Lee",
        "Leesburg",
        "Lighthouse Point",
        "Live Oak",
        "Longboat Key",
        "Longwood",
        "Loxahatchee Groves",
        "Lynn Haven",
        "Macclenny",
        "Madeira Beach",
        "Madison",
        "Maitland",
        "Malabar",
        "Malone",
        "Manalapan",
        "Mangonia Park",
        "Marathon",
        "Marco Island",
        "Margate",
        "Marianna",
        "Marineland",
        "Mary Esther",
        "Mascotte",
        "Mayo",
        "McIntosh",
        "Medley",
        "Melbourne Beach",
        "Melbourne Village",
        "Melbourne",
        "Mexico Beach",
        "Miami Beach",
        "Miami Gardens",
        "Miami Lakes",
        "Miami Shores",
        "Miami Springs",
        "Miami",
        "Micanopy",
        "Midway",
        "Milton",
        "Minneola",
        "Miramar",
        "Monticello",
        "Montverde",
        "Moore Haven",
        "Mount Dora",
        "Mulberry",
        "Naples",
        "Neptune Beach",
        "New Port Richey",
        "New Smyrna Beach",
        "Newberry",
        "Niceville",
        "Noma",
        "North Bay Village",
        "North Lauderdale",
        "North Miami Beach",
        "North Miami",
        "North Palm Beach",
        "North Port",
        "North Redington Beach",
        "Oak Hill",
        "Oakland Park",
        "Oakland",
        "Ocala",
        "Ocean Breeze",
        "Ocean Ridge",
        "Ocoee",
        "Okeechobee",
        "Oldsmar",
        "Opa-locka",
        "Orange City",
        "Orange Park",
        "Orchid",
        "Orlando",
        "Ormond Beach",
        "Otter Creek",
        "Oviedo",
        "Pahokee",
        "Palatka",
        "Palm Bay",
        "Palm Beach Gardens",
        "Palm Beach Shores",
        "Palm Beach",
        "Palm Coast",
        "Palm Shores",
        "Palm Springs",
        "Palmetto Bay",
        "Palmetto",
        "Panama City Beach",
        "Panama City",
        "Parker",
        "Parkland",
        "Paxton",
        "Pembroke Park",
        "Pembroke Pines",
        "Penney Farms",
        "Pensacola",
        "Perry",
        "Pierson",
        "Pinecrest",
        "Pinellas Park",
        "Plant City",
        "Plantation",
        "Polk City",
        "Pomona Park",
        "Pompano Beach",
        "Ponce Inlet",
        "Ponce de Leon",
        "Port Orange",
        "Port Richey",
        "Port St. Joe",
        "Port St. Lucie",
        "Punta Gorda",
        "Quincy",
        "Raiford",
        "Reddick",
        "Redington Beach",
        "Redington Shores",
        "Riviera Beach",
        "Rockledge",
        "Royal Palm Beach",
        "Safety Harbor",
        "San Antonio",
        "Sanford",
        "Sanibel",
        "Sarasota",
        "Satellite Beach",
        "Sea Ranch Lakes",
        "Sebastian",
        "Sebring",
        "Seminole",
        "Sewall’s Point",
        "Shalimar",
        "Sneads",
        "Sopchoppy",
        "South Bay",
        "South Daytona",
        "South Miami",
        "South Palm Beach",
        "South Pasadena",
        "Southwest Ranches",
        "Springfield",
        "St. Augustine Beach",
        "St. Augustine",
        "St. Cloud",
        "St. Leo",
        "St. Lucie Village",
        "St. Marks",
        "St. Pete Beach",
        "St. Petersburg",
        "Starke",
        "Stuart",
        "Sunny Isles Beach",
        "Sunrise",
        "Surfside",
        "Sweetwater",
        "Tallahassee #",
        "Tamarac",
        "Tampa",
        "Tarpon Springs",
        "Tavares",
        "Temple Terrace",
        "Tequesta",
        "Titusville",
        "Treasure Island",
        "Trenton",
        "Umatilla",
        "Valparaiso",
        "Venice",
        "Vernon",
        "Vero Beach",
        "Virginia Gardens",
        "Waldo",
        "Wauchula",
        "Wausau",
        "Webster",
        "Welaka",
        "Wellington",
        "West Melbourne",
        "West Miami",
        "West Palm Beach",
        "West Park",
        "Westlake",
        "Weston",
        "Westville",
        "Wewahitchka",
        "White Springs",
        "Wildwood",
        "Williston",
        "Wilton Manors",
        "Windermere",
        "Winter Garden",
        "Winter Haven",
        "Winter Park",
        "Winter Springs",
        "Worthington Springs",
        "Yankeetown",
        "Zephyrhills",
        "Zolfo Springs",
    ],
}
